## Numpy is the core library for scientific computing in Python. 

## It provides a high-performance multidimensional array object, and tools for working with these arrays. 

## If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

In [10]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"

<class 'numpy.ndarray'>
(3,)


In [26]:
b = np.array([[1,2,3,4,5],[4,5,6,1,0]])    # Create a rank 2 array
print(b.shape)

(2, 5)


In [11]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [12]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[1. 1.]]


In [13]:
c = np.full((2,2), 7)  # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [14]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [16]:
e = np.random.random((2,3))  # Create an array filled with random values
print(e)  

[[0.95033893 0.09108984 0.16694132]
 [0.37574085 0.9711961  0.68148016]]


In [17]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [20]:
b = a[:2, 1:3]

In [21]:
b

array([[2, 3],
       [6, 7]])

In [22]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [27]:
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

[[False False]
 [ True  True]
 [ True  True]]


In [28]:
import numpy as np   # Importing libraries

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
c = np.array([3, 5])

print("Matrix A\n", a)
print("Matrix B\n", b)

print("Regular matrix addition A+B\n", a + b)

print("Addition using Broadcasting A+5\n", a + 5)

Matrix A
 [0 1 2]
Matrix B
 [5 5 5]
Regular matrix addition A+B
 [5 6 7]
Addition using Broadcasting A+5
 [5 6 7]


In [31]:
a = np.array([[1,2], [3, 4], [5, 6]])
print("Transposed Matrix\n",a.T)

Transposed Matrix
 [[1 3 5]
 [2 4 6]]
