In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [3]:
import cv2

In [14]:
img=cv2.imread('raj1.jpg')

In [6]:
print(type(img))

<class 'numpy.ndarray'>


In [9]:
print(img.shape)

(134, 185, 3)


In [15]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
b=img[:,:,0]
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
print(b)

[[253 255 255 ... 255 255 255]
 [253 255 255 ... 255 255 255]
 [253 255 255 ... 255 255 255]
 ...
 [111 111 113 ... 217 201 188]
 [112 111 114 ... 245 242 238]
 [112 111 114 ... 255 255 255]]


In [ ]:
g=img[:,:,1]
r=img[:,:,2]
cv2.imshow('Blue',b)
cv2.imshow('Green',g)
cv2.imshow('Red',r)
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
cap=cv2.VideoCapture('C:/Users/Sachin/Desktop/Temp2/sach.mov')

if cap.isOpened()==False:
    print("Can't open video....")
    
while True:
    ret, frame=cap.read()
    
    if ret==True:
        cv2.imshow('Frame',frame)
        
        if cv2.waitKey(25) & 0xFF==27:
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()