In [3]:
# PyTorch aggregate functions
import torch

In [4]:
x=torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [5]:
print(f"Minimum value: {x.min()}")
print(f"Maimum value: {x.max()}")


Minimum value: 0
Maimum value: 95


In [8]:
print(f"Mean value: {x.type(torch.float32).mean()}")

Mean value: 47.5


In [9]:
torch.max(x)

tensor(95)

In [10]:
torch.min(x)

tensor(0)

In [11]:
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [13]:
torch.sum(x)

tensor(950)

In [14]:
#reshape
x=torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [15]:
x.dtype

torch.float32

In [16]:
x_reshaped=x.reshape(1,7)
x_reshaped.shape

torch.Size([1, 7])

In [18]:
x_reshaped[:,0]=7
x_reshaped

tensor([[7., 2., 3., 4., 5., 6., 7.]])

In [20]:
x_stack=torch.stack([x,x,x,x,x],dim=0)
x_stack

tensor([[7., 2., 3., 4., 5., 6., 7.],
        [7., 2., 3., 4., 5., 6., 7.],
        [7., 2., 3., 4., 5., 6., 7.],
        [7., 2., 3., 4., 5., 6., 7.],
        [7., 2., 3., 4., 5., 6., 7.]])

In [21]:
#image parametrs
x_original=torch.rand(size=(224,224,3))

In [22]:
x_original

tensor([[[0.8581, 0.6958, 0.2149],
         [0.5000, 0.6728, 0.9270],
         [0.9594, 0.6978, 0.4489],
         ...,
         [0.7143, 0.5118, 0.3860],
         [0.4034, 0.0382, 0.6675],
         [0.9454, 0.1632, 0.3132]],

        [[0.5999, 0.2670, 0.5904],
         [0.5444, 0.5282, 0.7186],
         [0.9252, 0.4924, 0.1839],
         ...,
         [0.4936, 0.6352, 0.4265],
         [0.7778, 0.5459, 0.9472],
         [0.4914, 0.2155, 0.2039]],

        [[0.3539, 0.5276, 0.2540],
         [0.0128, 0.5403, 0.4713],
         [0.6738, 0.4213, 0.3182],
         ...,
         [0.2946, 0.5311, 0.6587],
         [0.9507, 0.3284, 0.2596],
         [0.2588, 0.9619, 0.3535]],

        ...,

        [[0.7690, 0.0435, 0.3251],
         [0.6827, 0.0848, 0.5755],
         [0.4808, 0.8946, 0.1580],
         ...,
         [0.5336, 0.9950, 0.7562],
         [0.7794, 0.9434, 0.1431],
         [0.0455, 0.0290, 0.7778]],

        [[0.6759, 0.3856, 0.1442],
         [0.4803, 0.7835, 0.2760],
         [0.

In [23]:
x_permute=x_original.permute(2,0,1)

In [24]:
x_permute

tensor([[[0.8581, 0.5000, 0.9594,  ..., 0.7143, 0.4034, 0.9454],
         [0.5999, 0.5444, 0.9252,  ..., 0.4936, 0.7778, 0.4914],
         [0.3539, 0.0128, 0.6738,  ..., 0.2946, 0.9507, 0.2588],
         ...,
         [0.7690, 0.6827, 0.4808,  ..., 0.5336, 0.7794, 0.0455],
         [0.6759, 0.4803, 0.4632,  ..., 0.5671, 0.1016, 0.5037],
         [0.4928, 0.3753, 0.8284,  ..., 0.7704, 0.5833, 0.1052]],

        [[0.6958, 0.6728, 0.6978,  ..., 0.5118, 0.0382, 0.1632],
         [0.2670, 0.5282, 0.4924,  ..., 0.6352, 0.5459, 0.2155],
         [0.5276, 0.5403, 0.4213,  ..., 0.5311, 0.3284, 0.9619],
         ...,
         [0.0435, 0.0848, 0.8946,  ..., 0.9950, 0.9434, 0.0290],
         [0.3856, 0.7835, 0.9494,  ..., 0.0182, 0.5840, 0.6491],
         [0.4692, 0.8078, 0.2624,  ..., 0.2616, 0.7912, 0.5381]],

        [[0.2149, 0.9270, 0.4489,  ..., 0.3860, 0.6675, 0.3132],
         [0.5904, 0.7186, 0.1839,  ..., 0.4265, 0.9472, 0.2039],
         [0.2540, 0.4713, 0.3182,  ..., 0.6587, 0.2596, 0.

In [25]:

x_permute.shape

torch.Size([3, 224, 224])

In [26]:
x_original.shape


torch.Size([224, 224, 3])

In [34]:
#reshape again
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [41]:
print(x[0][2][2])

tensor(9)


In [43]:
print(x[:,2])

tensor([[7, 8, 9]])


In [44]:
print(x[:,1,1])

tensor([5])


In [45]:
import random

In [47]:
RANDOM_SEED=21
y=torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

In [48]:
y

In [49]:
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

In [50]:
random_tensor_D

tensor([[0.4736, 0.6136, 0.0121, 0.0396],
        [0.5674, 0.2538, 0.5338, 0.6093],
        [0.7162, 0.6043, 0.9980, 0.1445]])

In [51]:
random_tensor_C

tensor([[0.4736, 0.6136, 0.0121, 0.0396],
        [0.5674, 0.2538, 0.5338, 0.6093],
        [0.7162, 0.6043, 0.9980, 0.1445]])

In [52]:
random_tensor_D==random_tensor_C

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [53]:
#another device

!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [55]:
!pip install jupyterlab-nvdashboard

  Attempting uninstall: pywinpty
    Found existing installation: pywinpty 2.0.2
    Uninstalling pywinpty-2.0.2:
      Successfully uninstalled pywinpty-2.0.2


In [56]:
!jupyter labextension install jupyterlab-nvdashboard

An error occurred.
ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
See the log file for details:  C:\Users\Sachin\AppData\Local\Temp\jupyterlab-debug-sgtk2hin.log


In [57]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
