In [2]:
import torch

In [3]:
# Tensor data type
# scaler Vector Matrix Tensor
float_32_tensor=torch.tensor([3.0,6.5,8.2],dtype=None,device=None, requires_grad=True)

In [6]:
float_32_tensor.dtype

torch.float32

In [7]:
float_32_tensor=torch.tensor([3.0,6.5,8.2],dtype=torch.float16,device=None, requires_grad=True)

In [8]:
float_32_tensor.dtype

torch.float16

In [11]:
tensor_aim=torch.rand(3,4)

In [12]:
tensor_aim

tensor([[0.3338, 0.1617, 0.9949, 0.9915],
        [0.3998, 0.7583, 0.2600, 0.5045],
        [0.2976, 0.7994, 0.0274, 0.4566]])

In [13]:
print(tensor_aim)
print(f"Shape of Tensor: {tensor_aim.shape}")
print(f"Datatype of Tensor: {tensor_aim.dtype}")
print(f"Device of Tensor location: {tensor_aim.device}")

tensor([[0.3338, 0.1617, 0.9949, 0.9915],
        [0.3998, 0.7583, 0.2600, 0.5045],
        [0.2976, 0.7994, 0.0274, 0.4566]])
Shape of Tensor: torch.Size([3, 4])
Datatype of Tensor: torch.float32
Device of Tensor location: cpu


In [14]:
#TPU #GPU
#Manipulating Tensors


In [15]:
#Adding
tensor=torch.tensor([10,15,18])
tensor+10


tensor([20, 25, 28])

In [25]:
#substraction
tensor=torch.tensor([2,5,7])
tensor-10

tensor([-8, -5, -3])

In [28]:
#divide
tensor=torch.tensor([10,15,18])
tensor=tensor/10

In [29]:
tensor

tensor([1.0000, 1.5000, 1.8000])

In [18]:
#Multiplication
tensor=tensor*10

In [19]:
tensor

tensor([100, 150, 180])

In [22]:
tensor=torch.multiply(tensor,10)

In [23]:
tensor

tensor([1000, 1500, 1800])

In [24]:
#element wise multiplication
print(tensor*tensor)

tensor([1000000, 2250000, 3240000])


In [30]:
#Matrix Multiplication
#torch.matmul()
# (5,7)*(4,7) don't work
# (1,4)*(4,5) =(1,5) will work

In [31]:
tensor=torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [34]:
tensor_mul=torch.matmul(tensor,tensor)

In [36]:
tensor_mul 
#1*1+2*2+3*3=1+4+9=14

tensor(14)

In [37]:
tensor_mul=tensor@tensor

In [39]:
tensor_mul

tensor(14)

In [45]:
%%time 
tensor=torch.tensor([10,21,34])
tensor_mul=torch.matmul(tensor,tensor)
print(tensor_mul)

tensor(1697)
CPU times: total: 15.6 ms
Wall time: 1.97 ms
