In [8]:
import torch

In [9]:
torch.__version__

'1.12.1'

In [10]:
#scalers
scaler=torch.tensor(9)

In [11]:
scaler

tensor(9)

In [12]:
scaler.ndim

0

In [13]:
scaler.item()

9

In [18]:
#vector
vector=torch.tensor([8,5,3])

In [19]:
vector

tensor([8, 5, 3])

In [20]:
vector.ndim

1

In [21]:
vector.shape

torch.Size([3])

In [25]:
vector

tensor([8, 5, 3])

In [27]:
#Matrix
Matrix=torch.tensor([[1,5],[5,8]])

In [28]:
Matrix

tensor([[1, 5],
        [5, 8]])

In [29]:
Matrix.ndim

2

In [30]:
Matrix.shape

torch.Size([2, 2])

In [32]:
Tensor=torch.tensor([[[1,5,8],[7,9,5],[5,7,9]]])


In [33]:
Tensor

tensor([[[1, 5, 8],
         [7, 9, 5],
         [5, 7, 9]]])

In [34]:
Tensor.ndim

3

In [35]:
Tensor.shape

torch.Size([1, 3, 3])

In [37]:
#Random Tensor values 
random_tensor=torch.rand(size=(4,6))
random_tensor, random_tensor.dtype

(tensor([[0.3669, 0.1923, 0.0878, 0.3693, 0.7921, 0.8624],
         [0.5549, 0.8027, 0.5856, 0.2340, 0.1019, 0.5482],
         [0.4044, 0.6041, 0.8167, 0.1978, 0.1830, 0.2299],
         [0.2982, 0.6136, 0.5450, 0.9954, 0.0577, 0.9797]]),
 torch.float32)

In [38]:
random_image_size=torch.rand(size=(224,224,3))
random_image_size.shape, random_image_size.ndim 

(torch.Size([224, 224, 3]), 3)

In [39]:
random_image_size

tensor([[[0.6764, 0.4249, 0.0397],
         [0.1925, 0.6781, 0.1644],
         [0.1998, 0.7667, 0.1051],
         ...,
         [0.1204, 0.4478, 0.3123],
         [0.5605, 0.5934, 0.8585],
         [0.3474, 0.2525, 0.8879]],

        [[0.3547, 0.1765, 0.7534],
         [0.8105, 0.5017, 0.9243],
         [0.6433, 0.7274, 0.8627],
         ...,
         [0.5474, 0.8946, 0.9253],
         [0.0434, 0.5613, 0.3247],
         [0.3562, 0.6535, 0.6633]],

        [[0.6471, 0.7946, 0.3679],
         [0.3279, 0.4342, 0.9867],
         [0.9843, 0.9855, 0.2872],
         ...,
         [0.3206, 0.8770, 0.5055],
         [0.0498, 0.6761, 0.8324],
         [0.8467, 0.8097, 0.2134]],

        ...,

        [[0.8563, 0.2611, 0.4608],
         [0.8142, 0.6333, 0.6438],
         [0.9039, 0.3519, 0.9889],
         ...,
         [0.5956, 0.6263, 0.8264],
         [0.7591, 0.9079, 0.1923],
         [0.0806, 0.0410, 0.7335]],

        [[0.8001, 0.6745, 0.5689],
         [0.6564, 0.1747, 0.3640],
         [0.

In [41]:
zeros=torch.zeros(size=(3,4))

In [42]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
ones=torch.ones(size=(2,5))

In [44]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [45]:
start=0
end=10
step=2
arrrg=torch.arange(start,end,step)

In [46]:
arrrg

tensor([0, 2, 4, 6, 8])

In [47]:
zero_to_ten=torch.range(0,10)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_10076\340311480.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten=torch.range(0,10)


In [49]:
zero_to_ten=torch.ones_like(input=arrrg)
zero_to_ten

tensor([1, 1, 1, 1, 1])